version: 0.0
os: linux
files:
  - source: /
    destination: /var/node/grumbler
permissions:
  - object: .
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
hooks:
  BeforeInstall:
    - location: ./deploy/before-install.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: ./deploy/after-install.sh
      timeout: 60
      runas: ec2-user